server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /webshop
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_back?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    max-active: 20
    min-idle: 10
    max-wait: 10
  aop:
    auto: true
    proxy-target-class: true
  jpa:
    hibernate:
      ddl-auto: update #自动更新
    show-sql: true
    database: mysql
    properties:
     hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
logging:
  level:
    root: info
    com.zjl.webshop: debug
    org.springfromework.web: debug
    org.hibernate: error
mybatis:
  type-aliases-package: com.zjl.webshop.entity
  config-location: classpath:Mybatis/mybatis-config.xml
  mapper-locations: classpath:Mybatis/mapper/*.xml

